export const data = [
  {
    id: 1,
    title: "Kapüşonlu Uzun Kollu Baskılı Kalın Erkek Sweatshirt",
    price: 119.99,
    discount: 20,
    size: "M",
    colour: "Kırmızı",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 2,
    title: "LCW BASIC Kapüşonlu Uzun Kollu Fermuarlı Erkek Sweatshirt",
    price: 109.99,
    discount: 10,
    size: "M",
    colour: "Siyah",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 3,
    title: "LCW BASIC Kapüşonlu Uzun Kollu Fermuarlı Erkek Sweatshirt",
    price: 119.99,
    discount: 20,
    size: "M",
    colour: "Siyah",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 4,
    title: "LCW BASIC Bisiklet Yaka Uzun Kollu Kalın Erkek Sweatshirt",
    price: 89.99,
    discount: 5,
    size: "M",
    colour: "Haki",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 5,
    title: "LCW CASUAL Kapüşonlu Uzun Kollu Baskılı Erkek Sweatshirt",
    price: 119.99,
    discount: 10,
    size: "M",
    colour: "Siyah",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 6,
    title: "LCW CASUAL Kapüşonlu Uzun Kollu Baskılı Erkek Sweatshirt",
    price: 119.99,
    discount: 10,
    size: "M",
    colour: "Mavi",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 7,
    title: "LCW CASUAL Bisiklet Yaka Uzun Kollu Erkek Sweatshirt",
    price: 69.99,
    discount: 10,
    size: "M",
    colour: "Gri",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 8,
    title: "LCW CASUAL Kapüşonlu Fermuarlı Erkek Sweatshirt",
    price: 109.99,
    discount: 10,
    size: "M",
    colour: "Siyah",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 9,
    title: "Atatürk Baskılı Kapüşonlu Sweatshirt",
    price: 99.99,
    discount: 10,
    size: "M",
    colour: "Siyah",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 10,
    title: "Kapüşonlu Uzun Kollu Baskılı Kalın Erkek Sweatshirt",
    price: 119.99,
    discount: 20,
    size: "M",
    colour: "Beyaz",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 11,
    title: "Kapüşonlu Baskılı İnce Sweatshirt Baba Oğul Kombini",
    price: 99.99,
    discount: 20,
    size: "M",
    colour: "Siyah",
    number: "W1CE95Z8 - 998",
  },
  {
    id: 12,
    title: "Scooby-Doo Baskılı Sweatshirt",
    price: 119.99,
    discount: 10,
    size: "M",
    colour: "Krem",
    number: "W1CE95Z8 - 998",
  },
];
